/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_adhoc_manet_nativ_NativeTask */

#ifndef _Included_android_adhoc_manet_nativ_NativeTask
#define _Included_android_adhoc_manet_nativ_NativeTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_adhoc_manet_nativ_NativeTask
 * Method:    getProp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_adhoc_manet_nativ_NativeTask_getProp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_adhoc_manet_nativ_NativeTask
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_adhoc_manet_nativ_NativeTask_runCommand
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_adhoc_manet_nativ_NativeTask
 * Method:    runCommandGetOutput
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_adhoc_manet_nativ_NativeTask_runCommandGetOutput
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
